# Generated by Django 5.1.6 on 2025-04-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_hobby_result_subject_student_hobby_student_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.TextField(),
        ),
    ]
