# Generated by Django 5.1.6 on 2025-04-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_alter_student_city_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
