# Generated by Django 5.1.6 on 2025-04-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_alter_student_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Buddha', 'Buddha'), ('Atheist', 'Atheist')], max_length=50, null=True),
        ),
    ]
